"""Small ports for infrastructure and algorithm replacements.

The current adapters implement these ports with the prototype's real code.
Future work can provide Celery, PostGIS, embeddings, or CCDC adapters without
changing API handlers or the orchestration contract.
"""
from __future__ import annotations

from typing import Any, Callable, Protocol

from .repositories import RunRepository


Progress = Callable[[str, int, str], None]


class CatalogPort(Protocol):
    def search(self, source: str, bbox: tuple[float, float, float, float], start: str,
               end: str, cloud: int, limit: int) -> list[dict[str, Any]]: ...
    def coverage(self, items: list[dict[str, Any]]) -> dict[str, Any]: ...


class ImageryPort(Protocol):
    def optical_stack(self, items: list[dict[str, Any]], bbox: tuple[float, float, float, float],
                      want: tuple[str, ...], progress: Callable[[int, int], None]) -> list[dict[str, Any]]: ...
    def assemble(self, scenes: list[dict[str, Any]], want: tuple[str, ...],
                 min_valid: float) -> tuple[list[str], dict[str, Any], list[dict[str, Any]]]: ...
    def indices(self, stack: dict[str, Any]) -> dict[str, Any]: ...
    def read_window(self, href: str | None, bbox: tuple[float, float, float, float]) -> Any: ...
    def rgb_png(self, bands: dict[str, Any], path: str, **kwargs: Any) -> Any: ...


class SemanticRetrievalPort(Protocol):
    def parse(self, text: str) -> dict[str, Any]: ...
    def retrieve(self, text: str) -> dict[str, Any]: ...


class TemporalDetectionPort(Protocol):
    def to_cells(self, array: Any) -> Any: ...
    def select_dates(self, cube: Any, dates: list[str], min_cell_valid: float = 0.55,
                     need: int = 8) -> tuple[Any, float]: ...
    def fill_gaps(self, cube: Any) -> Any: ...
    def deseasonalize(self, cube: Any, dates: list[str], n_harm: int | None = None) -> Any: ...
    def multiscale_scan(self, composite: Any, ny: int, nx: int, sign: int = 0) -> tuple[Any, Any, Any]: ...
    def multiscale_null(self, composite: Any, ny: int, nx: int, sign: int = 0,
                        n_perm: int = 140, seed: int = 7, sample: int = 160) -> Any: ...
    def conformal_p(self, observed: Any, null: Any, sign: int = 0) -> Any: ...
    def amplitude_dispersion(self, stack: Any) -> Any: ...
    def db(self, stack: Any) -> Any: ...
    def spatial_smooth(self, residuals: Any, ny: int, nx: int, r: int = 1) -> Any: ...
    def scan_max_t(self, residuals: Any) -> tuple[Any, Any, Any]: ...


class SarEvidencePort(Protocol):
    def collect(self, bbox: tuple[float, float, float, float], start: str, end: str,
                split_date: str, ny: int, nx: int, progress: Progress) -> dict[str, Any] | None: ...


class RankingPort(Protocol):
    def context_bonus(self, context: dict[str, bool], pre_means: dict[str, Any]) -> Any: ...
    def linear_bonus(self, z: Any) -> Any: ...
    def ranks_of(self, score: Any, descending: bool = True) -> Any: ...
    def rrf(self, *rank_arrays: Any) -> Any: ...
    def bh_threshold(self, p: Any, alpha: float = 0.10) -> float: ...


class ConfirmationPort(Protocol):
    def confirm(self, detections: list[dict[str, Any]], progress: Progress) -> dict[str, Any]: ...


class ProvenancePort(Protocol):
    def new_chain(self) -> Any: ...
    def stac_refs(self, items: list[dict[str, Any]]) -> list[dict[str, Any]]: ...


class StoragePort(RunRepository, Protocol):
    def vectors(self, limit: int = 5000) -> list[dict[str, Any]]: ...
    """Application-facing alias for the persistence repository contract."""


class JobSubmissionPort(Protocol):
    def submit(self, request: dict[str, Any], work: Callable[[str, Progress], dict[str, Any]]) -> str: ...
    def status(self, job_id: str) -> dict[str, Any] | None: ...
